apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-log

  - name: almalinux
    image: almalinux:9
    command: ["sleep","100000"]
    volumeMounts:
    - mountPath: /mnt/nginx-log
      name: nginx-log
      readOnly: true
  volumes:
  - name: nginx-log
    emptyDir:
      sizeLimit: 100Mi