# it is kubernetes administrator job
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #retain means don't delete the data
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-04a3aba256cf343db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static # this PV name above is PV created
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi